# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}



//CAMISETAS

###
POST http://127.0.0.1:8000/camisetas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "nombre": "Camiseta Boca 1981 Diego Maradona titular",
        "año": 1981,
        "dorsal": 10,
        "jugador": "Maradona",
        "precio": 8000,
        "clubs":{
                "id":1
        }
}

###

DELETE http://127.0.0.1:8000/camisetas/5
Authorization: Bearer {{ login.response.body.token }}

###

PUT http://127.0.0.1:8000/camisetas/3
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "nombre": "Camiseta River 2021 Julian Alvarez titular",
        "año": 2021,
        "dorsal": 9,
        "jugador": "Alvarez",
        "precio": 5000,
        "clubs":{
                "id":2
        }
}




// CLUBES

###

DELETE http://127.0.0.1:8000/clubes/8
Authorization: Bearer {{ login.response.body.token }}

###

POST http://127.0.0.1:8000/clubes
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "nombre": "Huracan"
}

###

PUT http://127.0.0.1:8000/clubes/6
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "nombre": "San Lorenzo"
}

###




//USUARIOS

GET http://127.0.0.1:8000/usuarios
Authorization: Bearer {{ login.response.body.token }}

###

GET http://127.0.0.1:8000/usuarios?nombre=Lionel
Authorization: Bearer {{ login.response.body.token }}

###

GET http://127.0.0.1:8000/usuarios/2
Authorization: Bearer {{ login.response.body.token }}

###

DELETE http://127.0.0.1:8000/usuarios/3
Authorization: Bearer {{ login.response.body.token }}

###

PUT http://127.0.0.1:8000/usuarios/2
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "id":"2" ,
        "nombre": "Angel",
        "apellido": "Di Maria",
        "nickname": "fideo",
        "email": "fideo@gmail.com"
}