GET http://127.0.0.1:8000/clubes

###

GET http://127.0.0.1:8000/clubes?club=Boca

###

GET http://127.0.0.1:8000/clubes?multiclub=Boca,Racing

###

GET http://127.0.0.1:8000/clubes/1

###

DELETE http://127.0.0.1:8000/clubes/1

###

POST http://127.0.0.1:8000/clubes
Content-Type: application/json

{
        "club": "Velez"
}

###

PUT http://127.0.0.1:8000/clubes/2
Content-Type: application/json

{
        "id":"2" ,
        "club": "Huracan"
}