# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
POST http://127.0.0.1:8000/camisetas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "nombre": "Camiseta Boca 2016 Tevez titular",
        "año": 2016,
        "club": "Boca",
        "dorsal": 10,
        "jugador": "Tevez",
        "precio": 6000
}

###

DELETE http://127.0.0.1:8000/camisetas/1
Authorization: Bearer {{ login.response.body.token }}

###

PUT http://127.0.0.1:8000/camisetas/2 
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
        "id":"2",
        "nombre": "Camiseta River 1986 Alonso titular",
        "año": 1986,
        "club": "River",
        "dorsal": 10,
        "jugador": "Alonso",
        "precio": 6000

}